import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Index Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* For running React DevTools */}
      {/* <head>
        <script src="http://localhost:8097"></script>
      </head> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-h-dvh max-w-screen-lg flex flex-col m-auto px-3 lg:p-0`}
      >
        {children}
      </body>
    </html>
  );
}
